services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Greenfieldr\Golb\:
    resource: '../Classes/*'
  Greenfieldr\Golb\DataProcessing\MetaInformationProcessor:
    public: true

